from __future__ import annotations
from abc import ABC, abstractmethod


class StageInterface(ABC):
    @abstractmethod
    def home(self) -> None: ...
    @abstractmethod
    def move_absolute(self, axis1_mm: float, axis2_mm: float) -> None: ...
    @abstractmethod
    def move_relative(self, d_axis1_mm: float, d_axis2_mm: float) -> None: ...
    @abstractmethod
    def get_position(self) -> tuple[float, float]: ...
    @abstractmethod
    def stop(self) -> None: ...


class GripperInterface(ABC):
    @abstractmethod
    def open(self) -> None: ...
    @abstractmethod
    def close(self) -> None: ...
